### ISSUE TITLE
mhartid is MXLEN bits

### ISSUE THREAD

**Issue by jrtc27** [riscv-non-isa/riscv-uefi#2]
I know there are places where both Linux and FreeBSD assume hartids can fit in 32 bits, but since mhartid is an MXLEN-bit CSR shouldn't BootHartId be `OUT UINTN *`?

**Comment by vlsunil** [comment]
Thanks @jrtc27 !. Yes, will change to native. Good catch!

**Comment by vlsunil** [comment]
changed to UINTN in v0.2
